### PR TITLE
Stable/10

### PR DESCRIPTION
**Pull request by Mrt134**
Minor edits to the first half of 10.3 manual, capitalization and linking fixes.

### CODE REVIEW

**Comment by dlavigne** [comment]
wrt to capitalization of first word after a note, our policy has been to start with a lowercase. Do you have a compelling argument for changing this policy?

**Comment by Mrt134** [comment]
I compared it both ways, and I think it appears more appropriate to
capitalize the first word as the emphasis box appears to introduce a new
(related) thought or concept, self contained with a full sentence
structure. The words "note" or "warning" seem to exist as a separate
declaration and not as the introduction of the sentence within the emphasis
box, which would then indicate the first word of the actual sentence would
need to be capitalized.

**Comment by dlavigne** [comment]
OK. Since either is correct, let's save the warning/note changes until 11. wrt to the IceWM link, it is best to point to the official website when there is one. Can you please resync (as I did some link updates yesterday) and redo the patch without the warning/note and IceWM changes? Thanks!

**Comment by Mrt134** [comment]
Sure, I'll get it taken care of this afternoon!

**Pull request merged**
