### PR TITLE
Rename README.md to README

### PR DESCRIPTION
**Pull request by aaronraimist**
README.md needs to be renamed to README because it is not formatted for Markdown. When you view the file on GitHub a lot of formatting is lost because GitHub thinks the file is formatted for Markdown. This patch fixes README by making it be a regular file instead of a Markdown formatted file.

### CODE REVIEW

**Comment by skarekrow** [comment]
The README is using Markdown. By switching it to a file as you have, we lose that.

**Comment by aaronraimist** [comment]
@skarekrow It could also be changed to be formatted in Markdown but I don't think it currently is. For example compare the rendered README.md to the raw text: 
screenshot_2015-10-26_18-03-38

You can see the ```IRC (FreeNode)``` section is being rendered as if you wanted a header but you are really just listing IRC channels.

In the ```Source Map``` section all the text that is supposed to be on a separate line and indented is actually on the same line when rendered as Markdown.

You can also see that under the ```src-qt5/``` section the ```  % cd src-qt5 && /usr/local/lib/qt5/bin/qmake``` should be on a separate line but is actually put together with the previous line.

If you want it to be formatted in Markdown you could make some different changes but I don't think it is currently formatted correctly, if you keep the current text I think it looks better in plain text.

**Comment by skarekrow** [comment]
My apologies, you were 100% correct. I had not looked close enough. I pushed some changes into master, that I think look better. Any tweaks you think should be made are much appreciated!

**Comment by aaronraimist** [comment]
That looks good except for the `src-qt5` section since it has many more lines then the others. The "Note:" section could be moved to the bottom of the Source Map or extra space could be put around each section (see: https://gist.github.com/aaronraimist/2c24b6844c0a1d509cf2)

**Comment by skarekrow** [comment]
Appreciate that feedback @aaronraimist. I applied it to https://github.com/pcbsd/pcbsd/commit/6983bd42e13310334624924795728f19da8a3da5

**Pull request closed without merging**
