### PR TITLE
Anacron support for lpreserver scrub scheduling

### PR DESCRIPTION
**Pull request by bjar**
Note: Breaks the Life Preserver scrub scheduling GUI when scrub is scheduled with anacron.

### CODE REVIEW

**Comment by bjar** [comment]
Somewhat fixes this feature:
https://bugs.pcbsd.org/issues/11596

**Comment by kmoore134** [comment]
Fixes feature request #11596

**Comment by kmoore134** [comment]
Thanks for sending this in! I'll have Ken fix up the UI portion, but this is a good change.

**Comment by beanpole135** [comment]
GUI is fixed.

**Pull request merged**
