### PR TITLE
Sound output channel selection from mixer tray menu

### PR DESCRIPTION
**Pull request by yurkis**
This add sound output selection sub menu to the mixer tray popup menu.
When you sing laptop you should select sound output channel often (between internal speaker / headphones and for TV HDMI output). Each time when you should select output till now you need to open mixer UI, select configuration tab, and then choose output channel. IMHO more fast selection will be better.

### CODE REVIEW

**Comment by beanpole135** [comment]
Nice! Thanks for sending that in Yuri!
Would you mind adding the device-specific icons to the device selection combobox in the Mixer UI as well? I think that makes it a lot easier for people to select the right device... :-)

**Comment by yurkis** [comment]
I'm not sure is that icons will be right. I test it only on my personal laptop. It depends on some strings in device description. 
Can you check it on your hardware?

**Comment by beanpole135** [comment]
Yeah, I just tested it on my desktop and it only uses the generic icon for each item. Oh well....

**Comment by yurkis** [comment]
Can you give me your 'pc-sysconfig list-audiodev' output?

**Comment by beanpole135** [comment]
Sure thing!
pcm0: <Realtek ALC892 (Rear Analog 5.1/2.0)> (play/rec) default, pcm1: <Realtek ALC892 (Front Analog)> (play/rec), pcm2: <Realtek ALC892 (Onboard Digital)> (play), pcm3: <Realtek ALC892 (Rear Digital)> (play), pcm4: <USB audio> (rec)

As you can see, there are no specific/detailed labels aside from the front/rear descriptions. The record-only device (pcm4) is also listed in the menu by default, so we might want to hide these type of devices if it does not list the "play" status for it as well.

**Pull request merged**
