### PR TITLE
Add serial configuration

### PR DESCRIPTION
**Pull request by cthunter01**
Fixes issue with slow console output when not using serial output.

### CODE REVIEW

**Comment by kmoore134** [comment]
Is this related to the -D -h flags I was passing to the kernel via GRUB? I reverted those, found it causes issues on some systems. Instead I added a "serial mode" option to install media, which will re-enable those flags only if serial is needed. With that in mind, does your fix still apply?

**Comment by cthunter01** [comment]
Yes.

I noticed the change this morning, so I tested it after I saw it. Same 
issue, so I looked into it further. Before, I just hand edited the 
grub.cfg to take out the -D -h (and then the -Dh because that had the 
same issue). Then I wanted something more permanent and after reading 
some docs and the 10_ktrueos code I came to those lines.

There are some artifacts on the boot menu screen (but not the submenus), 
namely simultaneous console and gfx output, but it's pretty minor 
relative to the very slow output otherwise. So there is still a little 
something more that may be done to get rid of the artifact

**Comment by cthunter01** [comment]
Oh wait, I think I misread your message.

I thought you just changed -D -h to -Dh, which was the latest revision I 
had on my machine this morning. If you took out the -D -h flags, then 
no, that change shouldn't be relevant.

**Comment by kmoore134** [comment]
Closed since it no longer applies.

**Pull request closed without merging**
